#!/usr/bin/env bash
# Rabaska build. Produces dist/ ready to deploy as static files.
#
# The interesting part is why the wasm gets inlined as base64 rather than
# shipped as a sibling file.
#
# `wasm-pack --target web` generates glue that loads the module with
# `fetch('./rabaska_core_bg.wasm')`. Our CSP sets `connect-src 'none'`, which
# blocks fetch. That header is not incidental: it is the mechanism that makes
# "nothing leaves this machine" browser-enforced instead of a promise, and it is
# the thing a sceptical user can verify by reading response headers. Relaxing it
# to 'self' to let the loader work would trade the product's central claim for a
# build convenience.
#
# So the wasm is embedded in a JS module and instantiated from bytes. No fetch
# happens anywhere in the app, at any point, ever. Costs about 33% on the wire
# for a file that is cached permanently after first load, and as a bonus makes
# the single-file air-gap build fall out for free.

set -euo pipefail
cd "$(dirname "$0")"

OUT=dist
echo "==> cleaning"
rm -rf "$OUT" core/pkg
mkdir -p "$OUT"

# No C anywhere in the tree, so this needs nothing but rustup and wasm-pack.
echo "==> building wasm"
wasm-pack build core \
  --target web \
  --release \
  --out-dir pkg \
  --out-name rabaska_core \
  -- --features wasm

WASM=core/pkg/rabaska_core_bg.wasm
GLUE=core/pkg/rabaska_core.js
test -f "$WASM" || { echo "wasm-pack produced no wasm"; exit 1; }

echo "==> inlining wasm ($(wc -c <"$WASM" | tr -d ' ') bytes)"
python3 - "$WASM" "$OUT/wasm-inline.js" <<'PY'
import base64, sys
raw = open(sys.argv[1], 'rb').read()
b64 = base64.b64encode(raw).decode()
open(sys.argv[2], 'w').write(
    "// Generated by build.sh. Do not edit.\n"
    "// The wasm module lives here as base64 so the app never calls fetch(),\n"
    "// which lets the CSP keep connect-src 'none'. See build.sh.\n"
    f"const B64 = '{b64}';\n"
    "const bin = atob(B64);\n"
    "export const WASM_BYTES = new Uint8Array(bin.length);\n"
    "for (let i = 0; i < bin.length; i++) WASM_BYTES[i] = bin.charCodeAt(i);\n"
)
PY

echo "==> assembling"
cp "$GLUE" "$OUT/rabaska_core.js"
cp app/index.html app/app.js app/style.css app/manifest.webmanifest app/_headers "$OUT/"
cp app/icon-192.png app/icon-512.png app/*.woff2 "$OUT/"

# Build hash over every precached byte, not merely everything that executes.
#
# Two jobs ride on this number and only one of them was being served. The
# visible one: it is shown on both screens during a transfer, so two devices
# running different code is a glance apart. The silent one: the service worker
# names its cache `rabaska-$BUILD`, so the hash IS the cache key.
#
# It used to cover the wasm, the glue, app.js and index.html. A change to
# style.css therefore produced an identical hash, an identical sw.js, and a
# browser that correctly concluded there was nothing to update — leaving every
# device that had already loaded the app serving the old stylesheet forever. A
# stylesheet-only fix could not reach a single existing user, and nothing said
# so. The list is explicit and ordered rather than globbed, because a glob makes
# the hash depend on directory listing order.
BUILD=$(cat "$WASM" "$GLUE" \
  app/app.js app/sw.js app/index.html app/style.css \
  app/manifest.webmanifest app/icon-192.png app/icon-512.png \
  app/inter-var.woff2 app/jbmono-400.woff2 app/jbmono-500.woff2 \
  | shasum -a 256 | cut -c1-16)
echo "==> build hash: $BUILD"

# The service worker is generated from a template so the precache list can never
# drift from what is actually in dist/. A stale entry makes cache.addAll reject,
# which fails the whole install and leaves the app with no offline capability at
# all, silently.
PRECACHE=$(cd "$OUT" && ls | grep -v '^_headers$' | sed "s|^|    './|;s|$|',|" | sort)
python3 - "$OUT/sw.js" "$BUILD" <<PY
import sys
tpl = open('app/sw.js').read()
tpl = tpl.replace('__BUILD_HASH__', sys.argv[2])
precache = """$PRECACHE"""
start = tpl.index('const PRECACHE = [')
end = tpl.index('];', start) + 2
tpl = tpl[:start] + "const PRECACHE = [\n    './',\n" + precache + "\n];" + tpl[end:]
open(sys.argv[1], 'w').write(tpl)
PY

sed -i.bak "s|__BUILD_HASH__|$BUILD|g" "$OUT/app.js" && rm -f "$OUT/app.js.bak"

echo "==> verifying"
grep -q "__BUILD_HASH__" "$OUT"/*.js && { echo "FAIL: unsubstituted build hash"; exit 1; }
grep -q "connect-src 'none'" "$OUT/_headers" || { echo "FAIL: CSP lost connect-src none"; exit 1; }

# The page's connect-src must be 'none' and the service worker's must not be.
# A CSP served with a worker script governs that worker, and cache.addAll
# fetches through it: inheriting 'none' makes every precache fetch fail, the
# install reject, and the offline claim quietly stop being true. That exact
# combination shipped once. It does not get to ship twice.
#
# The count is checked as strictly as the content. Cloudflare APPENDS repeated
# headers across matching rules, and two policies on one response are both
# enforced — so a second CSP can only ever narrow the first. A `/sw.js` rule
# that looks like it grants 'self' grants nothing if a `/*` rule already said
# 'none'. This guard modelled the merge as a dict and so agreed with itself
# while the live origin served both headers and the precache failed for every
# user. Anything matching more than one CSP rule is the bug, whatever the
# policies say.
python3 - "$OUT/_headers" <<'PY'
import re, sys
rules, current = [], None
for line in open(sys.argv[1]):
    if not line.strip() or line.lstrip().startswith('#'):
        continue
    if not line.startswith((' ', '\t')):
        current = []
        rules.append((line.strip(), current))
    elif current is not None:
        k, _, v = line.strip().partition(':')
        current.append((k.strip(), v.strip()))


def csps_for(path):
    """Every CSP that would be sent on this path, in order. Not merged."""
    out = []
    for pattern, headers in rules:
        if re.match('^' + re.escape(pattern).replace(r'\*', '.*') + '$', path):
            out += [v for k, v in headers if k.lower() == 'content-security-policy']
    return out


for path in ('/', '/index.html', '/sw.js'):
    n = len(csps_for(path))
    if n != 1:
        sys.exit(f"FAIL: {path} would be served {n} Content-Security-Policy "
                 "headers. Browsers enforce all of them at once, so the "
                 "effective policy is their intersection and the narrower one "
                 "wins. Exactly one rule may set a CSP for any given path.")

page, worker = csps_for('/index.html')[0], csps_for('/sw.js')[0]
if "connect-src 'none'" not in page:
    sys.exit("FAIL: the page CSP must keep connect-src 'none'")
if csps_for('/')[0] != page:
    sys.exit("FAIL: / and /index.html must carry the same policy; both are "
             "precached and either can serve a navigation")
if "connect-src 'self'" not in worker:
    sys.exit("FAIL: /sw.js needs its own CSP with connect-src 'self', or the "
             "precache cannot fetch and the app silently loses offline support")
print('    CSP split verified: one policy per document, page none, worker self')
PY
if grep -n "fetch(" "$OUT/app.js" | grep -v '^\s*//'; then
  echo "FAIL: app.js calls fetch, which connect-src 'none' will block"; exit 1
fi
python3 - "$OUT" <<'PY'
import os, re, sys
d = sys.argv[1]
sw = open(os.path.join(d, 'sw.js')).read()
listed = re.findall(r"'\./([^']*)'", sw[sw.index('const PRECACHE'):sw.index('];')])
missing = [f for f in listed if f and not os.path.exists(os.path.join(d, f))]
if missing:
    sys.exit('FAIL: sw precaches files not in dist: ' + ', '.join(missing))
print('    precache manifest matches dist (%d entries)' % len(listed))
PY

echo "==> dist/ ready"
ls -la "$OUT"
