#!/usr/bin/env bash
# Rabaska build. Produces dist/ ready to deploy as static files.
#
# The interesting part is why the wasm gets inlined as base64 rather than
# shipped as a sibling file.
#
# `wasm-pack --target web` generates glue that loads the module with
# `fetch('./rabaska_core_bg.wasm')`. Our CSP sets `connect-src 'none'`, which
# blocks fetch. That header is not incidental: it is the mechanism that makes
# "nothing leaves this machine" browser-enforced instead of a promise, and it is
# the thing a sceptical user can verify by reading response headers. Relaxing it
# to 'self' to let the loader work would trade the product's central claim for a
# build convenience.
#
# So the wasm is embedded in a JS module and instantiated from bytes. No fetch
# happens anywhere in the app, at any point, ever. Costs about 33% on the wire
# for a file that is cached permanently after first load, and as a bonus makes
# the single-file air-gap build fall out for free.

set -euo pipefail
cd "$(dirname "$0")"

OUT=dist
echo "==> cleaning"
rm -rf "$OUT" core/pkg
mkdir -p "$OUT"

# No C anywhere in the tree, so this needs nothing but rustup and wasm-pack.
echo "==> building wasm"
wasm-pack build core \
  --target web \
  --release \
  --out-dir pkg \
  --out-name rabaska_core \
  -- --features wasm

WASM=core/pkg/rabaska_core_bg.wasm
GLUE=core/pkg/rabaska_core.js
test -f "$WASM" || { echo "wasm-pack produced no wasm"; exit 1; }

echo "==> inlining wasm ($(wc -c <"$WASM" | tr -d ' ') bytes)"
python3 - "$WASM" "$OUT/wasm-inline.js" <<'PY'
import base64, sys
raw = open(sys.argv[1], 'rb').read()
b64 = base64.b64encode(raw).decode()
open(sys.argv[2], 'w').write(
    "// Generated by build.sh. Do not edit.\n"
    "// The wasm module lives here as base64 so the app never calls fetch(),\n"
    "// which lets the CSP keep connect-src 'none'. See build.sh.\n"
    f"const B64 = '{b64}';\n"
    "const bin = atob(B64);\n"
    "export const WASM_BYTES = new Uint8Array(bin.length);\n"
    "for (let i = 0; i < bin.length; i++) WASM_BYTES[i] = bin.charCodeAt(i);\n"
)
PY

echo "==> assembling"
cp "$GLUE" "$OUT/rabaska_core.js"
cp app/index.html app/app.js app/style.css app/manifest.webmanifest app/_headers "$OUT/"
cp app/icon-192.png app/icon-512.png app/*.woff2 "$OUT/"

# Build hash over everything that executes. Displayed on both screens during a
# transfer, so two devices running different code is visible at a glance. It
# must therefore cover the glue and the app, not just the wasm.
BUILD=$(cat "$WASM" "$GLUE" app/app.js app/index.html | shasum -a 256 | cut -c1-16)
echo "==> build hash: $BUILD"

# The service worker is generated from a template so the precache list can never
# drift from what is actually in dist/. A stale entry makes cache.addAll reject,
# which fails the whole install and leaves the app with no offline capability at
# all, silently.
PRECACHE=$(cd "$OUT" && ls | grep -v '^_headers$' | sed "s|^|    './|;s|$|',|" | sort)
python3 - "$OUT/sw.js" "$BUILD" <<PY
import sys
tpl = open('app/sw.js').read()
tpl = tpl.replace('__BUILD_HASH__', sys.argv[2])
precache = """$PRECACHE"""
start = tpl.index('const PRECACHE = [')
end = tpl.index('];', start) + 2
tpl = tpl[:start] + "const PRECACHE = [\n    './',\n" + precache + "\n];" + tpl[end:]
open(sys.argv[1], 'w').write(tpl)
PY

sed -i.bak "s|__BUILD_HASH__|$BUILD|g" "$OUT/app.js" && rm -f "$OUT/app.js.bak"

echo "==> verifying"
grep -q "__BUILD_HASH__" "$OUT"/*.js && { echo "FAIL: unsubstituted build hash"; exit 1; }
grep -q "connect-src 'none'" "$OUT/_headers" || { echo "FAIL: CSP lost connect-src none"; exit 1; }
if grep -n "fetch(" "$OUT/app.js" | grep -v '^\s*//'; then
  echo "FAIL: app.js calls fetch, which connect-src 'none' will block"; exit 1
fi
python3 - "$OUT" <<'PY'
import os, re, sys
d = sys.argv[1]
sw = open(os.path.join(d, 'sw.js')).read()
listed = re.findall(r"'\./([^']*)'", sw[sw.index('const PRECACHE'):sw.index('];')])
missing = [f for f in listed if f and not os.path.exists(os.path.join(d, f))]
if missing:
    sys.exit('FAIL: sw precaches files not in dist: ' + ', '.join(missing))
print('    precache manifest matches dist (%d entries)' % len(listed))
PY

echo "==> dist/ ready"
ls -la "$OUT"
